// useMockData.js
export default function useMockData() {
  const loading = null;
  const error = null;
  const apiData =
// { // Solingen
//     "ip": "87.153.63.48",
//     "network": "87.153.48.0/20",
//     "version": "IPv4",
//     "city": "Solingen",
//     "region": "North Rhine-Westphalia",
//     "region_code": "NW",
//     "country": "DE",
//     "country_name": "Germany",
//     "country_code": "DE",
//     "country_code_iso3": "DEU",
//     "country_capital": "Berlin",
//     "country_tld": ".de",
//     "continent_code": "EU",
//     "in_eu": true,
//     "postal": "42719",
//     "latitude": 51.1789,
//     "longitude": 7.0444,
//     "timezone": "Europe/Berlin",
//     "utc_offset": "+0200",
//     "country_calling_code": "+49",
//     "currency": "EUR",
//     "currency_name": "Euro",
//     "languages": "de",
//     "country_area": 357021,
//     "country_population": 82927922,
//     "asn": "AS3320",
//     "org": "Deutsche Telekom AG"
//   }
// { // Bridgetown
//   "ip": "65.166.240.33",
//   "network": "65.166.240.0/21",
//   "version": "IPv4",
//   "city": "Bridgetown",
//   "region": "Saint Michael",
//   "region_code": "08",
//   "country": "BB",
//   "country_name": "Barbados",
//   "country_code": "BB",
//   "country_code_iso3": "BRB",
//   "country_capital": "Bridgetown",
//   "country_tld": ".bb",
//   "continent_code": "NA",
//   "in_eu": false,
//   "postal": null,
//   "latitude": 13.0961,
//   "longitude": -59.616,
//   "timezone": "America/Barbados",
//   "utc_offset": "-0400",
//   "country_calling_code": "+1-246",
//   "currency": "BBD",
//   "currency_name": "Dollar",
//   "languages": "en-BB",
//   "country_area": 431,
//   "country_population": 286641,
//   "asn": "AS14813",
//   "org": "BB-COLUMBUS"
// }
// { // Melbourne
//   "ip": "58.166.240.33",
//   "network": "58.166.240.0/21",
//   "version": "IPv4",
//   "city": "Melbourne",
//   "region": "Victoria",
//   "region_code": "VIC",
//   "country": "AU",
//   "country_name": "Australia",
//   "country_code": "AU",
//   "country_code_iso3": "AUS",
//   "country_capital": "Canberra",
//   "country_tld": ".au",
//   "continent_code": "OC",
//   "in_eu": false,
//   "postal": "3001",
//   "latitude": -37.8159,
//   "longitude": 144.9669,
//   "timezone": "Australia/Melbourne",
//   "utc_offset": "+1100",
//   "country_calling_code": "+61",
//   "currency": "AUD",
//   "currency_name": "Dollar",
//   "languages": "en-AU",
//   "country_area": 7686850,
//   "country_population": 24992369,
//   "asn": "AS1221",
//   "org": "Telstra Corporation Ltd"
// }
{ // Taipei
  "ip": "162.158.243.30",
  "network": "162.158.240.0/22",
  "version": "IPv4",
  "city": "Taipei",
  "region": "Taipei City",
  "region_code": "TPE",
  "country": "TW",
  "country_name": "Taiwan",
  "country_code": "TW",
  "country_code_iso3": "TWN",
  "country_capital": "Taipei",
  "country_tld": ".tw",
  "continent_code": "AS",
  "in_eu": false,
  "postal": null,
  "latitude": 25.0504,
  "longitude": 121.5324,
  "timezone": "Asia/Taipei",
  "utc_offset": "+0800",
  "country_calling_code": "+886",
  "currency": "TWD",
  "currency_name": "Dollar",
  "languages": "zh-TW,zh,nan,hak",
  "country_area": 35980,
  "country_population": 23451837,
  "asn": "AS13335",
  "org": "CLOUDFLARENET"
}

const moduleCalled = "Data faked by useMockData";

  return { loading, error, apiData, moduleCalled };
}
